const categoryPlural = {
  "berry": "berries",
  "mushroom": "mushrooms",
  "tree": "trees",
}

export {categoryPlural}

export default [
  {
    name: "Strawberry",
    category: "berry",
    qualities: ["Sweet", "Juicy", "Vitamin C Rich"],
    attributes: ["Red", "Small", "Soft"],
    vitality: 15,
    toxins: 0,
    satiety: 5,
  },
  {
    name: "Blueberry",
    category: "berry",
    qualities: ["Sweet", "Antioxidant Rich", "Tangy"],
    attributes: ["Small", "Blue", "Round"],
    vitality: 18,
    toxins: 0,
    satiety: 4,
  },
  {
    name: "Raspberry",
    category: "berry",
    qualities: ["Tangy", "Nutritious", "High Fiber"],
    attributes: ["Red", "Soft", "Clustered Shape"],
    vitality: 14,
    toxins: 0,
    satiety: 6,
  },
  {
    name: "Blackberry",
    category: "berry",
    qualities: ["Sweet", "Earthy Flavor", "Rich in Antioxidants"],
    attributes: ["Dark Purple", "Plump", "Clustered"],
    vitality: 20,
    toxins: 0,
    satiety: 7,
  },
  {
    name: "Goji Berry",
    category: "berry",
    qualities: ["Sweet", "Slightly Tart", "Superfood"],
    attributes: ["Orange-Red", "Elongated", "Textured"],
    vitality: 30,
    toxins: 0,
    satiety: 8,
  },
  {
    name: "Elderberry",
    category: "berry",
    qualities: ["Tart", "Boosts Immunity", "Medicinal"],
    attributes: ["Dark Purple", "Small", "Clustered"],
    vitality: 17,
    toxins: 1,
    satiety: 5,
  },
  {
    name: "Cranberry",
    category: "berry",
    qualities: ["Tart", "Vitamin C Rich", "Detoxifying"],
    attributes: ["Red", "Small", "Round"],
    vitality: 12,
    toxins: 0,
    satiety: 5,
  },
  {
    name: "Yellow Raspberry",
    category: "berry",
    qualities: ["Sweet", "Rare", "High Antioxidants"],
    attributes: ["Yellow", "Small", "Clustered"],
    vitality: 15,
    toxins: 0,
    satiety: 6,
  },
  {
    name: "Boysenberry",
    category: "berry",
    qualities: ["Tangy", "Unique Flavor", "Rich in Vitamins"],
    attributes: ["Dark Purple", "Large", "Clustered"],
    vitality: 18,
    toxins: 0,
    satiety: 7,
  },
  {
    name: "Cloudberry",
    category: "berry",
    qualities: ["Sweet", "Rare", "High in Vitamin C"],
    attributes: ["Yellow-Orange", "Soft", "Round"],
    vitality: 10,
    toxins: 0,
    satiety: 5,
  },
  {
    name: "Snowberry",
    category: "berry",
    qualities: ["Bitter", "Ornamental", "Potentially Toxic"],
    attributes: ["White", "Small", "Round"],
    vitality: 2,
    toxins: 15,
    satiety: 2,
  },
  {
    name: "Salmonberry",
    category: "berry",
    qualities: ["Mildly Sweet", "Juicy", "Unique Taste"],
    attributes: ["Orange", "Small", "Clustered"],
    vitality: 10,
    toxins: 0,
    satiety: 4,
  },
  {
    name: "Mulberry",
    category: "berry",
    qualities: ["Sweet", "Nutrient Dense", "Juicy"],
    attributes: ["Purple", "Elongated", "Soft"],
    vitality: 17,
    toxins: 0,
    satiety: 6,
  },
  {
    name: "Huckleberry",
    category: "berry",
    qualities: ["Sweet", "Fruity Flavor", "Rich in Antioxidants"],
    attributes: ["Dark Blue-Purple", "Small", "Round"],
    vitality: 18,
    toxins: 0,
    satiety: 5,
  },
  {
    name: "Wineberry",
    category: "berry",
    qualities: ["Sweet", "Tangy", "Uncommon"],
    attributes: ["Bright Red", "Small", "Clustered"],
    vitality: 12,
    toxins: 0,
    satiety: 4,
  },
  {
    name: "Bilberry",
    category: "berry",
    qualities: ["Sweet", "High in Flavonoids", "Rare"],
    attributes: ["Blue", "Small", "Round"],
    vitality: 15,
    toxins: 0,
    satiety: 5,
  },
  {
    name: "Lingonberry",
    category: "berry",
    qualities: ["Slightly Tart", "Medicinal Properties", "Vitamin Rich"],
    attributes: ["Red", "Small", "Round"],
    vitality: 14,
    toxins: 0,
    satiety: 4,
  },
  {
    name: "Porcini",
    category: "mushroom",
    qualities: ["Earthy", "Rich Flavor", "Gourmet"],
    attributes: ["Brown Cap", "Thick Stem", "Meaty Texture"],
    vitality: 25,
    toxins: 0,
    satiety: 10,
  },
  {
    name: "Shiitake",
    category: "mushroom",
    qualities: ["Umami Flavor", "Medicinal Properties", "Popular in Asian Cuisine"],
    attributes: ["Brown Cap", "Thin Stem", "Chewy Texture"],
    vitality: 20,
    toxins: 0,
    satiety: 8,
  },
  {
    name: "Chanterelle",
    category: "mushroom",
    qualities: ["Peppery", "Fragrant", "Nutritious"],
    attributes: ["Golden Yellow", "Trumpet Shape", "Firm"],
    vitality: 28,
    toxins: 0,
    satiety: 9,
  },
  {
    name: "Maitake",
    category: "mushroom",
    qualities: ["Woody", "Medicinal", "Rich in Vitamins"],
    attributes: ["Clustered", "Brown", "Soft"],
    vitality: 23,
    toxins: 0,
    satiety: 9,
  },
  {
    name: "Morel",
    category: "mushroom",
    qualities: ["Nutty", "Highly Prized", "Unique Flavor"],
    attributes: ["Honeycomb-Like Cap", "Brown", "Fragile"],
    vitality: 35,
    toxins: 0,
    satiety: 12,
  },
  {
    name: "Enoki",
    category: "mushroom",
    qualities: ["Mild Taste", "Crispy", "Used in Soups"],
    attributes: ["White", "Thin Stems", "Small Caps"],
    vitality: 12,
    toxins: 0,
    satiety: 6,
  },
  {
    name: "Truffle",
    category: "mushroom",
    qualities: ["Earthy", "Highly Prized", "Intense Aroma"],
    attributes: ["Dark", "Knobby", "Dense"],
    vitality: 40,
    toxins: 0,
    satiety: 15,
  },
  {
    name: "Puffball",
    category: "mushroom",
    qualities: ["Mild Taste", "Soft Texture", "Edible when Young"],
    attributes: ["Round", "White", "Smooth"],
    vitality: 12,
    toxins: 1,
    satiety: 4,
  },
  {
    name: "Honey Fungus",
    category: "mushroom",
    qualities: ["Distinct Flavor", "Grows in Clusters", "Edible"],
    attributes: ["Brown Caps", "Tough Stalks", "Soft Gills"],
    vitality: 8,
    toxins: 2,
    satiety: 4,
  },
  {
    name: "Velvet Foot",
    category: "mushroom",
    qualities: ["Mild Taste", "Common in Winter", "Edible"],
    attributes: ["Velvet-Like Stalk", "Brown Caps", "Small"],
    vitality: 10,
    toxins: 1,
    satiety: 5,
  },
  {
    name: "Red Champignon",
    category: "mushroom",
    qualities: ["Mild Flavor", "Bright Color", "Edible"],
    attributes: ["Red Cap", "Short Stalk", "Soft Gills"],
    vitality: 8,
    toxins: 2,
    satiety: 3,
  },
  {
    name: "Deadly Nightshade",
    category: "berry",
    qualities: ["Poisonous", "Bitter", "Dark History"],
    attributes: ["Black", "Glossy", "Small"],
    vitality: -10,
    toxins: 100,
    satiety: 1,
  },
  {
    name: "Holly Berry",
    category: "berry",
    qualities: ["Ornamental", "Brightly Colored", "Toxic"],
    attributes: ["Bright Red", "Round", "Hard"],
    vitality: -2,
    toxins: 50,
    satiety: 2,
  },
  {
    name: "Poison Ivy Berry",
    category: "berry",
    qualities: ["Highly Toxic", "Small", "Glossy"],
    attributes: ["White", "Clustered", "Smooth"],
    vitality: -5,
    toxins: 70,
    satiety: 0,
  },
  {
    name: "Snakeberry",
    category: "berry",
    qualities: ["Deceptively Sweet", "Mildly Toxic", "Juicy"],
    attributes: ["Red", "Small", "Glossy"],
    vitality: 2,
    toxins: 20,
    satiety: 4,
  },
  {
    name: "Bittersweet Nightshade",
    category: "berry",
    qualities: ["Highly Toxic", "Bitter", "Medicinal in Small Doses"],
    attributes: ["Purple-Black", "Small", "Teardrop"],
    vitality: -8,
    toxins: 80,
    satiety: 1,
  },
  {
    name: "Doll's Eyes",
    category: "berry",
    qualities: ["Extremely Toxic", "Glossy", "Unusual"],
    attributes: ["White", "Small", "Dark Pupil-Like Center"],
    vitality: -20,
    toxins: 120,
    satiety: 2,
  },
  {
    name: "Moonseed",
    category: "berry",
    qualities: ["Juicy", "Highly Toxic", "Rare"],
    attributes: ["Dark Purple", "Round", "Clustered"],
    vitality: -15,
    toxins: 90,
    satiety: 3,
  },
  {
    name: "Yew Berry",
    category: "berry",
    qualities: ["Highly Poisonous", "Ornamental", "Red and Glossy"],
    attributes: ["Bright Red", "Small", "Translucent"],
    vitality: -18,
    toxins: 85,
    satiety: 1,
  },
  {
    name: "Crowberry",
    category: "berry",
    qualities: ["Bitter", "Occasionally Toxic", "Black"],
    attributes: ["Dark Purple-Black", "Small", "Round"],
    vitality: 1,
    toxins: 35,
    satiety: 5,
  },
  {
    name: "Tangleberry",
    category: "berry",
    qualities: ["Twisting Vines", "Deceptive Appearance", "Mildly Toxic"],
    attributes: ["Red-Orange", "Small", "Clustered"],
    vitality: 2,
    toxins: 25,
    satiety: 3,
  },
  {
    name: "Fly Agaric",
    category: "mushroom",
    qualities: ["Hallucinogenic", "Brightly Colored", "Highly Toxic"],
    attributes: ["Red Cap", "White Spots", "Thin Stem"],
    vitality: -10,
    toxins: 100,
    satiety: 2,
  },
  {
    name: "Death Cap",
    category: "mushroom",
    qualities: ["Extremely Toxic", "Lethal", "Deceptively Edible"],
    attributes: ["White Cap", "Smooth", "Fragile"],
    vitality: -20,
    toxins: 150,
    satiety: 1,
  },
  {
    name: "Destroying Angel",
    category: "mushroom",
    qualities: ["Lethal", "Pure White", "Delicate"],
    attributes: ["Bright White", "Fragile", "Thin Stem"],
    vitality: -25,
    toxins: 150,
    satiety: 1,
  },
  {
    name: "Jack O'Lantern Mushroom",
    category: "mushroom",
    qualities: ["Glowing in the Dark", "Poisonous", "Unusual"],
    attributes: ["Bright Orange", "Clustered", "Thick Stem"],
    vitality: -8,
    toxins: 75,
    satiety: 3,
  },
  {
    name: "False Morel",
    category: "mushroom",
    qualities: ["Deceptive", "Toxic", "Brain-Like Appearance"],
    attributes: ["Brown", "Wrinkled", "Soft"],
    vitality: -10,
    toxins: 80,
    satiety: 2,
  },
  {
    name: "Panther Cap",
    category: "mushroom",
    qualities: ["Toxic", "Similar to Fly Agaric", "Psychoactive"],
    attributes: ["Brown Cap", "White Spots", "Thin Stem"],
    vitality: -12,
    toxins: 90,
    satiety: 2,
  },
  {
    name: "Woolly Milkcap",
    category: "mushroom",
    qualities: ["Potentially Toxic", "Milky Substance", "Hairy Cap"],
    attributes: ["Orange-Brown", "Rough Texture", "Short Stem"],
    vitality: -5,
    toxins: 50,
    satiety: 3,
  },
  {
    name: "Sulphur Tuft",
    category: "mushroom",
    qualities: ["Bright Yellow", "Highly Toxic", "Clustered Growth"],
    attributes: ["Yellow Caps", "Thin Stem", "Smooth"],
    vitality: -15,
    toxins: 85,
    satiety: 2,
  },
  {
    name: "Purple Sporecap",
    category: "mushroom",
    qualities: ["Psychoactive", "Rare", "Toxic in Large Quantities"],
    attributes: ["Purple Cap", "Thin Stem", "Smooth"],
    vitality: 5,
    toxins: 60,
    satiety: 1,
  },
  {
    name: "Bleeding Tooth Fungus",
    category: "mushroom",
    qualities: ["Unusual Appearance", "Oozes Red Liquid", "Mildly Toxic"],
    attributes: ["White", "Red Drops", "Soft"],
    vitality: -3,
    toxins: 30,
    satiety: 1,
  },
  {
    name: "Dead Man's Fingers",
    category: "mushroom",
    qualities: ["Creepy Appearance", "Moderately Toxic"],
    attributes: ["Black", "Finger-Like", "Rough Texture"],
    vitality: -5,
    toxins: 45,
    satiety: 2,
  }
];